Fix CD workflow
telerik/kendo-angular pull request #3254
Opened 2021-03-29 14:49 UTC by tsvetomir

* Projects were built twice.
* The branch check was wrong, but is also redundant.

2021-03-29 15:21 UTC, tapopov submitted a review, later dismissed

2021-03-29 18:23 UTC, ipeshev requested changes
if this is deleted https://github.com/telerik/kendo-angular/pull/3254/files#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18L37 why to keep license activation and npm ci steps ?

2021-03-29 18:24 UTC, ipeshev requested changes
if this is deleted https://github.com/telerik/kendo-angular/pull/3254/files#diff-ea3ea8c9932adc7ba8161ceda844fedd43b006848ef1140c050cbd7ea0788a18L37 why to keep license activation and npm ci steps ?

2021-03-30 05:21 UTC, tsvetomir commented
It's not needed as the publish script also [builds](https://github.com/telerik/kendo-angular/blob/97ce6bfea68926f95ae4dff203f1073c718dc3f4/examples/bin/publish-gh-pages#L17) the examples.

2021-03-30 15:26 UTC, merged