Coffee Warehouse app
telerik/kendo-angular pull request #3285
Opened 2021-04-26 07:30 UTC by mbechev

2021-04-27 05:06 UTC, ipeshev requested changes
Step for this project is missing in https://github.com/telerik/kendo-angular/blob/master/.github/workflows/ci.yml.

2021-04-27 09:48 UTC, dtopalov requested changes
Great job! I am not sure about this, but all custom component styling could go to global scss files, imported in the main scss file to avoid setting the encapsulation to None in multiple components. @inikolova ?

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/components/info/info.component.html
> +                            >Styling</a
perhaps the link should be to kendo-angular?

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/app.component.html
> +<kendo-drawer-container>
I would order the bindings a bit - each on a separate line when there is more than 1

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/components/dashboard/chart/chart.component.html
> +            <button kendoButton [toggleable]="true" [selected]="true" (click)="selectedChart = 'Trend'">{{customMsgService.translate('trend')}}</button>
ditto -order bindings

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/components/profile/profile.component.ts
> +            reader.onloadend = function () {
could be an arrow function to avoid "this" surprises

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/models/order.model.ts
> +    public customerContactName: string;
align fields

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/models/team.model.ts
> +	public teamID: number;
ditto

2021-04-27 09:48 UTC, dtopalov commented on examples-standalone/coffee-warehouse/src/app/resources/locales.js
> +    {
Suggestion: alignment could be 
```
[{
    prop1: value1...
}, {
    prop1: value1...
}, {
    prop1: value1...
}...]
```

2021-04-28 07:37 UTC, inikolova commented
On the Team Calendar page names are h1 elements - HTML page should contain a single h1 tag. Please change them to <span> or </p>

2021-04-28 11:05 UTC, dtopalov commented
Looks very good! Some areas for improvement:

- Linting errors should be fixed so that the build passes;

- Changing the theme from default to bootstrap causes the language dropdown text to be cut off:

    ![image](https://user-images.githubusercontent.com/7533599/116393035-d4aa7b00-a829-11eb-8fc2-7901fe565376.png)

- There should be a clear indication that uploading a profile picture is expected, not a random file:

    ![image](https://user-images.githubusercontent.com/7533599/116393248-13d8cc00-a82a-11eb-9b8b-2a7429b39981.png)

    The purpose of the upload could be made clearer by changing the button text to "Upload a profile picture" or similar; some validation could be added to the Upload (for example for the allowed extensions - jpg, jpeg, png)
- Saving the changes performed on the Profile change perhaps should not open the home page, there is no obvious connection between editing the profile details, and auto-routing to the home page afterwards. Displaying the profile info in read-only format, or showing some notification that the details are updated successfully instead seems more reasonable from an UX point of view.

2021-04-28 15:01 UTC, mbechev commented
Thank you guys for all the suggestions and your professional view of things. I believe that we make an amazing application together 🙏🏽 .

2021-04-28 15:12 UTC, dtopalov submitted a review, later dismissed

2021-04-29 07:09 UTC, inikolova approved these changes

2021-04-29 07:10 UTC, inikolova commented
Great job, @mbechev ! An amazing app indeed :)

2021-04-29 07:21 UTC, tsvetomir reviewed
Nice work ⚒️

2021-04-29 07:21 UTC, tsvetomir commented on examples-standalone/coffee-warehouse/README.md
> +This Kendo UI for Angular sample project demonstrates how to use [Kendo UI for Angular components](https://www.telerik.com/kendo-angular-ui/components) within a coffee warehouse prototype application
Wrong URL, also it's not included in [the list](https://github.com/telerik/kendo-angular/blob/e620e46b7a55eb628c4f4049e5856d099bdff0bd/examples/bin/build-gh-pages#L6) of published apps.

2021-04-29 07:21 UTC, tsvetomir commented on examples-standalone/coffee-warehouse/src/polyfills.ts
> +// import 'classlist.js';  // Run `npm install --save classlist.js`.
Maybe add those for IE11.

2021-04-29 07:21 UTC, tsvetomir commented on examples-standalone/coffee-warehouse/src/polyfills.ts
> +// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
Ditto.

2021-04-29 13:03 UTC, ipeshev submitted a review, later dismissed

2021-04-29 14:21 UTC, Raisolution approved these changes
Amazing job! Thank you everyone for the effort! ❤️

2021-04-29 14:48 UTC, dtopalov approved these changes

2021-04-29 14:59 UTC, merged